#!/bin/bash -e

ORG_PATH="github.com/coreos"
REPO_PATH="${ORG_PATH}/fleet"

echo "Building fleetd..."
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build -a -installsuffix cgo -ldflags '-s' -o bin/fleetd ${REPO_PATH}/fleetd

echo "Building fleetctl..."
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build -a -installsuffix cgo -ldflags '-s' -o bin/fleetctl ${REPO_PATH}/fleetctl
